Fixed

diff --git a/.github/workflows/on-demand-publish-docker-image.yml b/.github/workflows/on-demand-publish-docker-image.yml
--- a/.github/workflows/on-demand-publish-docker-image.yml
+++ b/.github/workflows/on-demand-publish-docker-image.yml
@@ -23,9 +23,28 @@ on:
         type: string
 
 jobs:
+  calculate-base-image-tag:
+    name: Calculate hash for base image
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - name: Calculate hash of package-lock.json
+        id: hash
+        run: |
+          if [ -f package-lock.json ]; then
+            echo "HASH=$(sha256sum package-lock.json | awk '{print $1}')" >> $GITHUB_ENV
+          else
+            echo "package-lock.json not found, exiting."
+            exit 1
+          fi
+
+      - name: Set hash tag
+        run: echo "BUILD_IMAGE_TAG=ghcr.io/wepublish/base-image:${{ env.HASH }}" >> $GITHUB_ENV
+
   build-and-push-docker-api:
     name: Build and push api
     runs-on: ubuntu-latest
+    needs: calculate-base-image-tag
     if: inputs.api_tags != ''
     steps:
       - uses: actions/checkout@v4
@@ -48,10 +67,11 @@ jobs:
           tags: |
             ${{ inputs.api_tags }}
           build-args:
-            BUILD_IMAGE=${{ inputs.base_image_tag }}
+            BUILD_IMAGE=${{ env.BUILD_IMAGE_TAG }}
   build-and-push-docker-editor:
     name: Build and push editor
     runs-on: ubuntu-latest
+    needs: calculate-base-image-tag
     if: inputs.editor_tags != ''
     steps:
       - uses: actions/checkout@v4
@@ -74,7 +94,7 @@ jobs:
           tags: |
             ${{ inputs.editor_tags }}
           build-args:
-            BUILD_IMAGE=${{ inputs.base_image_tag }}
+            BUILD_IMAGE=${{ env.BUILD_IMAGE_TAG }}
   build-and-push-docker-migration:
     name: Build and push migration
     runs-on: ubuntu-latest
@@ -126,6 +146,7 @@ jobs:
   build-and-push-storybook:
     name: Build and push storybook
     runs-on: ubuntu-latest
+    needs: calculate-base-image-tag
     if: inputs.storybook_tags != ''
     steps:
       - uses: actions/checkout@v4
@@ -148,4 +169,4 @@ jobs:
           tags: |
             ${{ inputs.storybook_tags }}
           build-args:
-            BUILD_IMAGE=${{ inputs.base_image_tag }}
+            BUILD_IMAGE=${{ env.BUILD_IMAGE_TAG }}
